sudo: required
services: required
  - docker
before_install:
  - docker build -f Dockerfile.dev -t saikrishna1501/docker-react .
script:
  - docker run -e CI=true docker run saikrishna1501/docker-react npm run test -- --coverage
